### ISSUE TITLE
Aeldari - Ynnari - Missing Tantalus/Reaper

### ISSUE THREAD

**Issue by shadowseercb** [BSData/wh40k#1058]
Hello, the Ynnari file is missing the forge world Dark Eldar Tantalus and the Reaper on the list.  My files are up to date.  Thanks for the great work!

**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by FarseerVeraenthis** [comment]
Hmmm... perhaps they were missed off the last merge...
@USSX-Hares this one is for you :smile:

**Comment by USSX-Hares** [comment]
Should be fixed in #1127

**Comment by shadowseercb** [comment]
I have deleted my roster and added it again on both my computer and phone.  The Tantalus and Reaper are still not on the list.

**Comment by FarseerVeraenthis** [comment]
Sorry for that, it must have missed the last release so the latest version of the file is not available on appspot, I'll sort a release out shortly and so it should be available within the next 24 hours...

**Comment by shadowseercb** [comment]
So hi, I hate to keep bugging you guys like this. But... Can you please add the Dark Eldar Reaper and Tantalus to the ynnari Army list please. Thank you

**Comment by shadowseercb** [comment]
Please add the Tantalus.

Thanks for adding the Reaper.  But the Tantalus didn't make it even though I see the name in the code.

**Comment by FarseerVeraenthis** [comment]
Argh! Those things are like the bane of my life!!

**Comment by shadowseercb** [comment]
Lol, the Dark Eldar bring the pain.  Thanks
