### ISSUE TITLE
Inquisition Land Raider Prometheus with individual Inquisitor 

### ISSUE THREAD

**Issue by foznoth** [BSData/wh40k#6706]
File: Imperium - Adeptus Ministorum.catz

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** No

**Description:** When adding an Inquisitor, the Inquisition Land Raider Prometheus should be enabled as a transport option. 
Obviously max 1.
This will affect all Imperium data files.

**Comment by alphalas** [comment]
Just add a inq child detachment.

**Comment by foznoth** [comment]
It's not a separate detachment though. The rules in the WD say that the Inquisitor is included in the main detachment.
There are a limit of the number of detachments that can be taken in an army, this would break that too.

**Comment by alphalas** [comment]
> There are a limit of the number of detachments that can be taken in an army, this would break that too.

There are a *SUGGESTED* limit to the number of detachments that can be taken in a *MATCHED PLAY* army.

Fixed it for you.

**Comment by alphalas** [comment]
ALSO, there is nothing on the data sheet that specifically says in inquisitor can take that land raider as a dedicated transport; ergo, you still need a detachment with the correct keywords to take it. This isn’t seventh edition were dedicated transport were assigned to specific units.

**Comment by foznoth** [comment]
Still doesn't fix the error in doing things properly? The Inquisitor is in the detachment, not an added detachment. The ability to add the Inquisitor is already in the data pack. So if someone was to do it as the rules dictate, then they can't add the transport.
Also please don't be patronising, we're all adults here. 
If that was my attitude on call logging when I was fixing issues, I'd have been sacked. 
I'm appreciative of the voluntary effort that goes in to these things, but it's no excuse for impoliteness.

**Comment by alphalas** [comment]
The rule that allows you to take an inquisitor, explicitly states you can take AN inquisitor. That’s it. You still would need an ordo detachment (because you can’t have an imperium detachment) to be able to have the Prometheus in your army.

**Comment by foznoth** [comment]
It is my understanding that the transport is taken against the keywords of the unit, not the detachment.
The Land Raider Prometheus is a dedicated transport for the Inquisition.
Though neither of us has rules to back that up, and GW are not the best for answering rules questions. I think we'll call this a no score draw, I'll do it your way, but see if I can get clarification out of GW (unlikely)

**Comment by foznoth** [comment]
Rules as written, one Inquisitor unit may be taken.
Then in FAQ 1.6 it says a transport can be taken for each unit.

**Comment by alphalas** [comment]
All units must share one keyword in a detachment, and IMPERIUM is not a legal keyword. The inquisitor is a **VERY SPECIFIC** exception to this, and explicitly states that it’s only that inquisitor that is allowed so the detachment is still battle forged.

**Comment by foznoth** [comment]
No, it says one Inquisitor unit, not that it's all or nothing

**Comment by alphalas** [comment]
So sure, you can take a DT for him **FROM THE DETACHMENT HE’S ATTACHED TO**, abiding by the battle forged rules for detachments.

**Comment by alphalas** [comment]
You’re missing the point, the LRP **IS A SEPARATE UNIT**

**Comment by alphalas** [comment]
It is **NOT** a sub-unit. This is not how 8e works - in 7e you would be correct.

**Comment by foznoth** [comment]
OK, I think we are hitting symantics.
On page 11 of the Rules FAQ 1.6 it says you can take a transport option for each unit included in the detachment. Though I cannot find anything that clears up which keywords should be used.
I think we are going around in circles. I'll fire off a question to GW and keep my fingers crossed. 
Thank you for the robust discussion.

**Comment by GenWilhelm** [comment]
As it stands right now, all units in a detachment must have at least one faction keyword in common (excluding IMPERIUM in this case).

The inquisition army rules say that you may include one inquisitor in any detachment, specifically ignoring the aforementioned rule for that model.

So, other than that one inquisitor, all other units in the detachment still have to have a faction keyword in common, which the Land Raider would not.

**Comment by alphalas** [comment]
Also, there is something we all overlooked. Dedicated Transports are a specific battlefield role now. The LRP is *NOT* DT, it’s a Heavy Support unit.

**Comment by foznoth** [comment]
I've not come across that. Where is it written?
Not being difficult, just want to get everything right.

**Comment by alphalas** [comment]
![2172C60B-20EE-4151-AD37-A0694B56E04C](https://user-images.githubusercontent.com/15703066/73976356-2188f580-48f6-11ea-98c8-0e6ab802c539.png)
![18272274-12AB-43DB-8FED-8CA3FAECAFAA](https://user-images.githubusercontent.com/15703066/73976360-251c7c80-48f6-11ea-9152-4f228436c70d.png)
![9CA05127-ABE4-4580-A21A-1576BF8C570C](https://user-images.githubusercontent.com/15703066/73976362-264da980-48f6-11ea-9d2f-eed2b2648bd3.png)

**Comment by foznoth** [comment]
Yep, just checked that myself. It has the transport keyword, but not the role. Just catching up. So as it stands, you are perfectly correct on the most simple of errors on my part. Damn, now I need to find another excuse to spend £85
